{% set name = "pyside2qtads" %}
{% set version = "4.0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mborgerson/pyside6_qtads/archive/v{{ version }}.tar.gz
  sha256: c010c8b3ed7c31ae293393f1cf1411ca58bafaf4cd9e13e140c4df88410cd3f7
  patches:
    - 0001-CMakeLists.patch
    - 0002-generate_pyi.patch
    - 0003-setup.patch
    - 0004-bindings.patch
    - 0005-init.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  ignore_run_exports_from:
    # Just used for shiboken/pyside not used for python module
    - clangdev  # [not osx]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clangdev
    - ninja
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('libxext') }}           # [linux]

  host:
    - python
    - cmake-build-extension
    - qt-main
    - qt5-advanced-docking-system
    - pyside2
    - pip
    - setuptools
    - xorg-libxfixes                 # [linux]
    
  run:
    - python
    - pyside2
    
test:
  imports:
    - PySide2QtAds

about:
  home: https://github.com/mborgerson/pyside6_qtads
  license: LGPL-2.1-only
  license_file: LICENSE
  summary: PySide2 bindings for Qt-Advanced-Docking-System

extra:
  recipe-maintainers:
    - n-elie
